<?php

declare(strict_types=1);

use Lettermint\ApiObject;
use Lettermint\Internal\Query;
use Lettermint\Types\CursorPage;
use Lettermint\Types\DomainData;
use Lettermint\Types\DomainDnsRecordData;
use Lettermint\Types\ListDomainsQuerySortItem;
use Lettermint\Types\ListDomainsResponse;
use Lettermint\Types\MessageStatus;
use Lettermint\Types\Operations;
use Lettermint\Types\SendMailResponse;
use Lettermint\Types\WebhookEvent;

describe('generated types', function () {
    it('hydrates nested objects and keeps the JSON as sent', function () {
        $json = [
            'id' => 'd1', 'domain' => 'acme.com', 'status_changed_at' => null,
            'dns_records' => [['id' => 'r1', 'type' => 'TXT', 'some_future_field' => 1]],
            'some_future_field' => ['x' => 1],
        ];
        $domain = DomainData::from($json);
        expect($domain->dns_records[0] ?? null)->toBeInstanceOf(DomainDnsRecordData::class)
            ->and($domain->dns_records[0]->type ?? null)->toBe('TXT')
            ->and($domain['dns_records'][0]['some_future_field'] ?? null)->toBe(1)
            ->and($domain->get('some_future_field'))->toBe(['x' => 1])
            ->and($domain->toArray())->toBe($json)
            ->and(json_decode((string) json_encode($domain), true))->toBe($json);
    });

    it('keeps optional (absent) and nullable (null) apart', function () {
        $domain = DomainData::from(['id' => 'd1', 'status_changed_at' => null]);
        expect($domain->status_changed_at)->toBeNull()
            ->and($domain->has('status_changed_at'))->toBeTrue()
            ->and($domain->dns_records)->toBeNull()
            ->and($domain->has('dns_records'))->toBeFalse()
            ->and(isset($domain->id))->toBeTrue()
            ->and(isset($domain->status_changed_at))->toBeFalse();
    });

    it('never fails on unexpected shapes', function () {
        $domain = DomainData::from(['dns_records' => 'not a list', 'projects' => [['a' => 1], 'x']]);
        expect($domain->dns_records)->toBe('not a list')
            ->and($domain->projects[1] ?? null)->toBe('x');
    });

    it('is read-only', function () {
        $domain = DomainData::from(['id' => 'd1']);
        expect(fn () => $domain->id = 'x')->toThrow(LogicException::class)
            ->and(fn () => $domain['id'] = 'x')->toThrow(LogicException::class);
    });

    it('serializes an empty object as {}', function () {
        expect(json_encode(DomainData::from([])))->toBe('{}');
    });

    it('has open enums with constants for the known values', function () {
        $response = SendMailResponse::from(['message_id' => 'm', 'status' => 'some_future_status']);
        expect($response->status)->toBe('some_future_status')
            ->and(MessageStatus::DELIVERED)->toBe('delivered')
            ->and(MessageStatus::VALUES)->toContain('pending')
            ->and(WebhookEvent::MESSAGE_DELIVERED)->toBe('message.delivered')
            ->and(ListDomainsQuerySortItem::CREATED_AT_DESC)->toBe('-created_at');
    });

    it('types every list response as a CursorPage', function () {
        foreach (Operations::ALL as $key => $operation) {
            if ($operation['pagination'] === null) {
                continue;
            }
            $class = 'Lettermint\\Types\\'.$operation['response']['type'];
            expect(is_subclass_of($class, CursorPage::class))->toBeTrue($key);
        }
        expect(ListDomainsResponse::from(['data' => []]))->toBeInstanceOf(CursorPage::class);
    });

    it('names a class or an ApiTypes alias for every type in the operation table', function () {
        $aliases = [];
        preg_match_all('/@phpstan-type (\w+) /', (string) file_get_contents(__DIR__.'/../src/Types/ApiTypes.php'), $matches);
        $aliases = array_flip($matches[1]);
        foreach (Operations::ALL as $key => $operation) {
            $names = [$operation['response']['type'], $operation['request']['type'] ?? null, $operation['query'], $operation['pagination']['items'] ?? null];
            foreach ($operation['errors'] as $errorTypes) {
                array_push($names, ...$errorTypes);
            }
            foreach (array_filter($names) as $name) {
                if (in_array($name, ['text', 'empty'], true)) {
                    continue;
                }
                expect(class_exists('Lettermint\\Types\\'.$name) || isset($aliases[$name]))->toBeTrue("{$key}: {$name}");
            }
        }
    });

    it('keeps the generated files untouched', function () {
        $files = glob(__DIR__.'/../src/Types/*.php') ?: [];
        expect(count($files))->toBeGreaterThan(150);
        $headers = [];
        foreach ($files as $file) {
            $lines = array_slice(preg_split('/\\r?\\n/', (string) file_get_contents($file)) ?: [], 2, 5);
            expect($lines[0])->toBe('// Generated by lettermint/sdk-generator — do not edit.')
                ->and($lines[1])->toMatch('/^\/\/ Spec: lettermint\/lettermint@[0-9a-f]{40}/')
                ->and($lines[2])->toMatch('/^\/\/ sending-openapi\.json SHA-256: [0-9a-f]{64}$/')
                ->and($lines[3])->toMatch('/^\/\/ team-openapi\.json SHA-256: [0-9a-f]{64}$/')
                ->and($lines[4])->toBe('// Naming profile: next');
            $headers[implode("\n", $lines)] = true;
        }
        expect($headers)->toHaveCount(1);
    });

    it('extends ApiObject in every generated response class', function () {
        foreach (glob(__DIR__.'/../src/Types/*.php') ?: [] as $file) {
            $class = 'Lettermint\\Types\\'.basename($file, '.php');
            $reflection = new ReflectionClass($class);
            $constants = $reflection->getConstants();
            $isHolder = in_array($reflection->getShortName(), ['ApiTypes', 'Operations'], true) || array_key_exists('VALUES', $constants);
            expect($isHolder || $reflection->isSubclassOf(ApiObject::class))->toBeTrue($class);
        }
    });
});

describe('query serialization', function () {
    it('handles scalars, dates, nesting and empty values like the Node SDK', function () {
        expect(Query::serialize([]))->toBe('')
            ->and(urldecode(Query::serialize([
                'a' => 1,
                'b' => true,
                'c' => false,
                'd' => null,
                'f' => [],
                'g' => ['x', 'y'],
                'h' => ['i' => 'j', 'k' => ['l' => 'm']],
                'n' => new DateTimeImmutable('2026-01-02T04:04:05+01:00'),
                'page[size]' => 5,
                'o' => [['p' => 1], ['p' => 2]],
            ])))->toBe('a=1&b=1&c=0&g=x,y&h[i]=j&h[k][l]=m&n=2026-01-02T03:04:05.000Z&page[size]=5&o[0][p]=1&o[1][p]=2');
    });

    it('encodes reserved characters like URLSearchParams', function () {
        expect(Query::serialize(['filter' => ['search' => 'a&b=c #d*~é']]))->toBe('filter%5Bsearch%5D=a%26b%3Dc+%23d*%7E%C3%A9');
    });

    it('sets top-level and bracketed parameters without changing the input', function () {
        $query = ['page' => ['size' => 2], 'page[cursor]' => 'old'];
        expect(Query::with($query, 'page[cursor]', 'next'))->toBe(['page' => ['size' => 2, 'cursor' => 'next']])
            ->and(Query::with([], 'cursor', 'c'))->toBe(['cursor' => 'c'])
            ->and($query)->toBe(['page' => ['size' => 2], 'page[cursor]' => 'old']);
    });
});
