<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class AnalyticsCatalogueGroupDimension
{
    public const PROJECT_ID = 'project_id';
    public const ROUTE_ID = 'route_id';
    public const MESSAGE_TYPE = 'message_type';
    public const SENDING_DOMAIN = 'sending_domain';
    public const RECIPIENT_DOMAIN = 'recipient_domain';
    public const PROVIDER_FAMILY = 'provider_family';
    public const PROVIDER_SUBTYPE = 'provider_subtype';
    public const FROM_ADDRESS = 'from_address';
    public const SUBJECT = 'subject';
    public const DEDICATED_IP = 'dedicated_ip';
    public const DEDICATED_POOL_ID = 'dedicated_pool_id';
    public const INFRASTRUCTURE_STATE = 'infrastructure_state';
    public const SMTP_CODE = 'smtp_code';
    public const ENHANCED_STATUS_CODE = 'enhanced_status_code';
    public const ENHANCED_STATUS_CATEGORY = 'enhanced_status_category';
    public const BOUNCE_CLASSIFICATION = 'bounce_classification';
    public const FAILURE_REASON = 'failure_reason';
    public const SMTP_RESPONSE_GROUP = 'smtp_response_group';
    public const ENGAGEMENT_STATE = 'engagement_state';
    public const REQUEST_ACTOR = 'request_actor';
    public const PROXY_TYPE = 'proxy_type';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::PROJECT_ID,
        self::ROUTE_ID,
        self::MESSAGE_TYPE,
        self::SENDING_DOMAIN,
        self::RECIPIENT_DOMAIN,
        self::PROVIDER_FAMILY,
        self::PROVIDER_SUBTYPE,
        self::FROM_ADDRESS,
        self::SUBJECT,
        self::DEDICATED_IP,
        self::DEDICATED_POOL_ID,
        self::INFRASTRUCTURE_STATE,
        self::SMTP_CODE,
        self::ENHANCED_STATUS_CODE,
        self::ENHANCED_STATUS_CATEGORY,
        self::BOUNCE_CLASSIFICATION,
        self::FAILURE_REASON,
        self::SMTP_RESPONSE_GROUP,
        self::ENGAGEMENT_STATE,
        self::REQUEST_ACTOR,
        self::PROXY_TYPE,
    ];

    private function __construct()
    {
    }
}
