<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * A filter operator.
 *
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class AnalyticsFilterOperator
{
    public const EQ = 'eq';
    public const IN = 'in';
    public const NOT_IN = 'not_in';
    public const IS_NULL = 'is_null';
    public const IS_NOT_NULL = 'is_not_null';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::EQ,
        self::IN,
        self::NOT_IN,
        self::IS_NULL,
        self::IS_NOT_NULL,
    ];

    private function __construct()
    {
    }
}
