<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Analytics results with their window metadata and pagination.
 *
 * @property-read AnalyticsResults $data
 * @property-read AnalyticsMeta $meta
 * @property-read AnalyticsPagination $pagination
 */
final class AnalyticsResponse extends ApiObject
{
    protected const CASTS = [
        'data' => AnalyticsResults::class,
        'meta' => AnalyticsMeta::class,
        'pagination' => AnalyticsPagination::class,
    ];
}
