<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * A metric from the analytics catalogue.
 *
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class AnalyticsMetric
{
    public const ACCEPTED = 'accepted';
    public const PROCESSED = 'processed';
    public const SUPPRESSED = 'suppressed';
    public const POLICY_REJECTED = 'policy_rejected';
    public const APPLICATION_FAILED = 'application_failed';
    public const MTA_ACCEPTED = 'mta_accepted';
    public const CANCELED = 'canceled';
    public const MESSAGES = 'messages';
    public const DELIVERED = 'delivered';
    public const BOUNCED = 'bounced';
    public const SOFT_BOUNCED = 'soft_bounced';
    public const ADMINISTRATIVELY_BOUNCED = 'administratively_bounced';
    public const DEFERRED_RECIPIENTS = 'deferred_recipients';
    public const DEFERRED_EVENTS = 'deferred_events';
    public const DELIVERY_ATTEMPTS = 'delivery_attempts';
    public const ATTEMPTED_RECIPIENTS = 'attempted_recipients';
    public const TRANSPORT_OUTCOME_RECIPIENTS = 'transport_outcome_recipients';
    public const EFFECTIVE_DELIVERED = 'effective_delivered';
    public const OPEN_TRACKED_DELIVERED = 'open_tracked_delivered';
    public const CLICK_TRACKED_DELIVERED = 'click_tracked_delivered';
    public const OUT_OF_BAND_BOUNCED_RECIPIENTS = 'out_of_band_bounced_recipients';
    public const OUT_OF_BAND_BOUNCE_EVENTS = 'out_of_band_bounce_events';
    public const COMPLAINED = 'complained';
    public const UNSUBSCRIBED = 'unsubscribed';
    public const HUMAN_OPENS = 'human_opens';
    public const HUMAN_OPENS_EVENTS = 'human_opens_events';
    public const HUMAN_CLICKS = 'human_clicks';
    public const HUMAN_CLICKS_EVENTS = 'human_clicks_events';
    public const MACHINE_OPENS = 'machine_opens';
    public const MACHINE_OPENS_EVENTS = 'machine_opens_events';
    public const MACHINE_CLICKS = 'machine_clicks';
    public const MACHINE_CLICKS_EVENTS = 'machine_clicks_events';
    public const PRIVACY_OPENS = 'privacy_opens';
    public const PRIVACY_OPENS_EVENTS = 'privacy_opens_events';
    public const PRIVACY_CLICKS = 'privacy_clicks';
    public const PRIVACY_CLICKS_EVENTS = 'privacy_clicks_events';
    public const BOT_OPENS = 'bot_opens';
    public const BOT_OPENS_EVENTS = 'bot_opens_events';
    public const BOT_CLICKS = 'bot_clicks';
    public const BOT_CLICKS_EVENTS = 'bot_clicks_events';
    public const SCANNER_OPENS = 'scanner_opens';
    public const SCANNER_OPENS_EVENTS = 'scanner_opens_events';
    public const SCANNER_CLICKS = 'scanner_clicks';
    public const SCANNER_CLICKS_EVENTS = 'scanner_clicks_events';
    public const OBSERVED_OPENS = 'observed_opens';
    public const OBSERVED_OPENS_EVENTS = 'observed_opens_events';
    public const OBSERVED_CLICKS = 'observed_clicks';
    public const OBSERVED_CLICKS_EVENTS = 'observed_clicks_events';
    public const DELIVERY_RATE = 'delivery_rate';
    public const EFFECTIVE_DELIVERY_RATE = 'effective_delivery_rate';
    public const BOUNCE_RATE = 'bounce_rate';
    public const DEFERRAL_RATE = 'deferral_rate';
    public const COMPLAINT_RATE = 'complaint_rate';
    public const HUMAN_OPEN_RATE = 'human_open_rate';
    public const HUMAN_CLICK_RATE = 'human_click_rate';
    public const PROCESSING_LATENCY_P50_MS = 'processing_latency_p50_ms';
    public const PROCESSING_LATENCY_P95_MS = 'processing_latency_p95_ms';
    public const PROCESSING_LATENCY_P99_MS = 'processing_latency_p99_ms';
    public const PROCESSING_LATENCY_SAMPLES = 'processing_latency_samples';
    public const DELIVERY_LATENCY_P50_MS = 'delivery_latency_p50_ms';
    public const DELIVERY_LATENCY_P95_MS = 'delivery_latency_p95_ms';
    public const DELIVERY_LATENCY_P99_MS = 'delivery_latency_p99_ms';
    public const DELIVERY_LATENCY_SAMPLES = 'delivery_latency_samples';
    public const TOTAL_LATENCY_P50_MS = 'total_latency_p50_ms';
    public const TOTAL_LATENCY_P95_MS = 'total_latency_p95_ms';
    public const TOTAL_LATENCY_P99_MS = 'total_latency_p99_ms';
    public const TOTAL_LATENCY_SAMPLES = 'total_latency_samples';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::ACCEPTED,
        self::PROCESSED,
        self::SUPPRESSED,
        self::POLICY_REJECTED,
        self::APPLICATION_FAILED,
        self::MTA_ACCEPTED,
        self::CANCELED,
        self::MESSAGES,
        self::DELIVERED,
        self::BOUNCED,
        self::SOFT_BOUNCED,
        self::ADMINISTRATIVELY_BOUNCED,
        self::DEFERRED_RECIPIENTS,
        self::DEFERRED_EVENTS,
        self::DELIVERY_ATTEMPTS,
        self::ATTEMPTED_RECIPIENTS,
        self::TRANSPORT_OUTCOME_RECIPIENTS,
        self::EFFECTIVE_DELIVERED,
        self::OPEN_TRACKED_DELIVERED,
        self::CLICK_TRACKED_DELIVERED,
        self::OUT_OF_BAND_BOUNCED_RECIPIENTS,
        self::OUT_OF_BAND_BOUNCE_EVENTS,
        self::COMPLAINED,
        self::UNSUBSCRIBED,
        self::HUMAN_OPENS,
        self::HUMAN_OPENS_EVENTS,
        self::HUMAN_CLICKS,
        self::HUMAN_CLICKS_EVENTS,
        self::MACHINE_OPENS,
        self::MACHINE_OPENS_EVENTS,
        self::MACHINE_CLICKS,
        self::MACHINE_CLICKS_EVENTS,
        self::PRIVACY_OPENS,
        self::PRIVACY_OPENS_EVENTS,
        self::PRIVACY_CLICKS,
        self::PRIVACY_CLICKS_EVENTS,
        self::BOT_OPENS,
        self::BOT_OPENS_EVENTS,
        self::BOT_CLICKS,
        self::BOT_CLICKS_EVENTS,
        self::SCANNER_OPENS,
        self::SCANNER_OPENS_EVENTS,
        self::SCANNER_CLICKS,
        self::SCANNER_CLICKS_EVENTS,
        self::OBSERVED_OPENS,
        self::OBSERVED_OPENS_EVENTS,
        self::OBSERVED_CLICKS,
        self::OBSERVED_CLICKS_EVENTS,
        self::DELIVERY_RATE,
        self::EFFECTIVE_DELIVERY_RATE,
        self::BOUNCE_RATE,
        self::DEFERRAL_RATE,
        self::COMPLAINT_RATE,
        self::HUMAN_OPEN_RATE,
        self::HUMAN_CLICK_RATE,
        self::PROCESSING_LATENCY_P50_MS,
        self::PROCESSING_LATENCY_P95_MS,
        self::PROCESSING_LATENCY_P99_MS,
        self::PROCESSING_LATENCY_SAMPLES,
        self::DELIVERY_LATENCY_P50_MS,
        self::DELIVERY_LATENCY_P95_MS,
        self::DELIVERY_LATENCY_P99_MS,
        self::DELIVERY_LATENCY_SAMPLES,
        self::TOTAL_LATENCY_P50_MS,
        self::TOTAL_LATENCY_P95_MS,
        self::TOTAL_LATENCY_P99_MS,
        self::TOTAL_LATENCY_SAMPLES,
    ];

    private function __construct()
    {
    }
}
