<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * The time window and data availability of the results.
 *
 * @property-read string $time_basis Known values: AnalyticsMetaTimeBasis::*.
 * @property-read string $timezone
 * @property-read string $interval Known values: AnalyticsInterval::*.
 * @property-read string $from Start of the window read, aligned down to the alignment grain.
 * @property-read string $to Exclusive end of the window, aligned up to the alignment grain.
 * @property-read string $effective_to Exclusive end of the counted data: to, or generated_at while the window is ongoing.
 * @property-read string $alignment Grain the requested boundaries were widened to: whole UTC hours, or whole UTC days for personal-data dimensions. Counts cover exactly from to effective_to. Known values: AnalyticsMetaAlignment::*.
 * @property-read string $generated_at
 * @property-read string $available_since
 * @property-read bool $partial
 * @property-read bool $ongoing
 * @property-read string $collection_completeness Known values: AnalyticsMetaCollectionCompleteness::*.
 * @property-read string|null $last_ingested_at Latest ingestion among matching rollup rows. This is not a completeness watermark.
 * @property-read string $metric_definition_version
 * @property-read int $ranked_group_limit
 * @property-read AnalyticsMetaComparison|null $comparison Optional.
 */
final class AnalyticsMeta extends ApiObject
{
    protected const CASTS = [
        'comparison' => AnalyticsMetaComparison::class,
    ];
}
