<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Numerators and denominators of the selected rate metrics.
 *
 * @property-read AnalyticsRateBase|null $delivery_rate Optional.
 * @property-read AnalyticsRateBase|null $effective_delivery_rate Optional.
 * @property-read AnalyticsRateBase|null $bounce_rate Optional.
 * @property-read AnalyticsRateBase|null $deferral_rate Optional.
 * @property-read AnalyticsRateBase|null $complaint_rate Optional.
 * @property-read AnalyticsRateBase|null $human_open_rate Optional.
 * @property-read AnalyticsRateBase|null $human_click_rate Optional.
 */
final class AnalyticsRateBases extends ApiObject
{
    protected const CASTS = [
        'delivery_rate' => AnalyticsRateBase::class,
        'effective_delivery_rate' => AnalyticsRateBase::class,
        'bounce_rate' => AnalyticsRateBase::class,
        'deferral_rate' => AnalyticsRateBase::class,
        'complaint_rate' => AnalyticsRateBase::class,
        'human_open_rate' => AnalyticsRateBase::class,
        'human_click_rate' => AnalyticsRateBase::class,
    ];
}
