<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Numerators and denominators of the selected rate metrics.
 *
 * @property-read AnalyticsRateBase|null $delivery_rate Optional.
 * @property-read AnalyticsRateBase|null $effective_delivery_rate Optional.
 * @property-read AnalyticsRateBase|null $bounce_rate Optional.
 * @property-read AnalyticsRateBase|null $deferral_rate Optional.
 * @property-read AnalyticsRateBase|null $complaint_rate Optional.
 * @property-read AnalyticsRateBase|null $human_open_rate Optional.
 * @property-read AnalyticsRateBase|null $human_click_rate Optional.
 */
final class AnalyticsRateBases extends ApiObject
{
    protected const CASTS = [
        'delivery_rate' => AnalyticsRateBase::class,
        'effective_delivery_rate' => AnalyticsRateBase::class,
        'bounce_rate' => AnalyticsRateBase::class,
        'deferral_rate' => AnalyticsRateBase::class,
        'complaint_rate' => AnalyticsRateBase::class,
        'human_open_rate' => AnalyticsRateBase::class,
        'human_click_rate' => AnalyticsRateBase::class,
    ];
}
