<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Values of the selected metrics. Rates are fractions; null when not available.
 *
 * @property-read int|null $accepted Optional.
 * @property-read int|null $processed Optional.
 * @property-read int|null $suppressed Optional.
 * @property-read int|null $policy_rejected Optional.
 * @property-read int|null $application_failed Optional.
 * @property-read int|null $mta_accepted Optional.
 * @property-read int|null $canceled Optional.
 * @property-read int|null $messages Optional.
 * @property-read int|null $delivered Optional.
 * @property-read int|null $bounced Optional.
 * @property-read int|null $soft_bounced Optional.
 * @property-read int|null $administratively_bounced Optional.
 * @property-read int|null $deferred_recipients Optional.
 * @property-read int|null $deferred_events Optional.
 * @property-read int|null $delivery_attempts Optional.
 * @property-read int|null $attempted_recipients Optional.
 * @property-read int|null $transport_outcome_recipients Optional.
 * @property-read int|null $effective_delivered Optional.
 * @property-read int|null $open_tracked_delivered Optional.
 * @property-read int|null $click_tracked_delivered Optional.
 * @property-read int|null $out_of_band_bounced_recipients Optional.
 * @property-read int|null $out_of_band_bounce_events Optional.
 * @property-read int|null $complained Optional.
 * @property-read int|null $unsubscribed Optional.
 * @property-read int|null $human_opens Optional.
 * @property-read int|null $human_opens_events Optional.
 * @property-read int|null $human_clicks Optional.
 * @property-read int|null $human_clicks_events Optional.
 * @property-read int|null $machine_opens Optional.
 * @property-read int|null $machine_opens_events Optional.
 * @property-read int|null $machine_clicks Optional.
 * @property-read int|null $machine_clicks_events Optional.
 * @property-read int|null $privacy_opens Optional.
 * @property-read int|null $privacy_opens_events Optional.
 * @property-read int|null $privacy_clicks Optional.
 * @property-read int|null $privacy_clicks_events Optional.
 * @property-read int|null $bot_opens Optional.
 * @property-read int|null $bot_opens_events Optional.
 * @property-read int|null $bot_clicks Optional.
 * @property-read int|null $bot_clicks_events Optional.
 * @property-read int|null $scanner_opens Optional.
 * @property-read int|null $scanner_opens_events Optional.
 * @property-read int|null $scanner_clicks Optional.
 * @property-read int|null $scanner_clicks_events Optional.
 * @property-read int|null $observed_opens Optional.
 * @property-read int|null $observed_opens_events Optional.
 * @property-read int|null $observed_clicks Optional.
 * @property-read int|null $observed_clicks_events Optional.
 * @property-read float|int|null $delivery_rate Optional.
 * @property-read float|int|null $effective_delivery_rate Optional.
 * @property-read float|int|null $bounce_rate Optional.
 * @property-read float|int|null $deferral_rate Optional.
 * @property-read float|int|null $complaint_rate Optional.
 * @property-read float|int|null $human_open_rate Optional.
 * @property-read float|int|null $human_click_rate Optional.
 * @property-read float|int|null $processing_latency_p50_ms Optional.
 * @property-read float|int|null $processing_latency_p95_ms Optional.
 * @property-read float|int|null $processing_latency_p99_ms Optional.
 * @property-read int|null $processing_latency_samples Optional.
 * @property-read float|int|null $delivery_latency_p50_ms Optional.
 * @property-read float|int|null $delivery_latency_p95_ms Optional.
 * @property-read float|int|null $delivery_latency_p99_ms Optional.
 * @property-read int|null $delivery_latency_samples Optional.
 * @property-read float|int|null $total_latency_p50_ms Optional.
 * @property-read float|int|null $total_latency_p95_ms Optional.
 * @property-read float|int|null $total_latency_p99_ms Optional.
 * @property-read int|null $total_latency_samples Optional.
 */
final class AnalyticsMetricValues extends ApiObject
{
}
