<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Metric values for one group of dimension values.
 *
 * @property-read AnalyticsMetricValues $metrics
 * @property-read AnalyticsRateBases $rate_bases
 * @property-read AnalyticsComparisonValues|null $previous Optional.
 * @property-read array<string, AnalyticsMetricChange>|null $change Optional.
 * @property-read array<string, string|null> $dimensions
 * @property-read list<AnalyticsTimeSeriesPoint>|null $trend Optional.
 */
final class AnalyticsBreakdownRow extends ApiObject
{
    protected const CASTS = [
        'metrics' => AnalyticsMetricValues::class,
        'rate_bases' => AnalyticsRateBases::class,
        'previous' => AnalyticsComparisonValues::class,
        'change' => ['map', AnalyticsMetricChange::class],
        'trend' => ['list', AnalyticsTimeSeriesPoint::class],
    ];
}
