<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Metric values for one time-series bucket.
 *
 * @property-read AnalyticsMetricValues $metrics
 * @property-read AnalyticsRateBases $rate_bases
 * @property-read AnalyticsComparisonValues|null $previous Optional.
 * @property-read array<string, AnalyticsMetricChange>|null $change Optional.
 * @property-read string $from
 * @property-read string $to
 * @property-read bool $available
 * @property-read bool $partial
 */
final class AnalyticsTimeSeriesPoint extends ApiObject
{
    protected const CASTS = [
        'metrics' => AnalyticsMetricValues::class,
        'rate_bases' => AnalyticsRateBases::class,
        'previous' => AnalyticsComparisonValues::class,
        'change' => ['map', AnalyticsMetricChange::class],
    ];
}
