<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Metric values for one group of dimension values.
 *
 * @property-read AnalyticsMetricValues $metrics
 * @property-read AnalyticsRateBases $rate_bases
 * @property-read AnalyticsComparisonValues|null $previous Optional.
 * @property-read array<string, AnalyticsMetricChange>|null $change Optional.
 * @property-read array<string, string|null> $dimensions
 * @property-read list<AnalyticsTimeSeriesPoint>|null $trend Optional.
 */
final class AnalyticsBreakdownRow extends ApiObject
{
    protected const CASTS = [
        'metrics' => AnalyticsMetricValues::class,
        'rate_bases' => AnalyticsRateBases::class,
        'previous' => AnalyticsComparisonValues::class,
        'change' => ['map', AnalyticsMetricChange::class],
        'trend' => ['list', AnalyticsTimeSeriesPoint::class],
    ];
}
