<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * PHPStan types for request bodies, query parameters and the API types that are
 * not classes. Import them with `@phpstan-import-type Name from ApiTypes`.
 *
 * Optional keys (`key?:`) may be left out; nullable values (`T|null`) may be `null`.
 * Enum values are typed as `string`, because the API may add values; the
 * constants of the enum classes list the known ones.
 *
 * @phpstan-type AnalyticsDimension string
 * @phpstan-type AnalyticsFilter array{dimension: string, operator: string, values?: list<string>}
 * @phpstan-type AnalyticsGroupDimension string
 * @phpstan-type AnalyticsQuery array{metrics: list<string>, from?: string, to?: string, timezone?: string, include?: list<string>, group_by?: list<string>, filters?: list<AnalyticsFilter>, interval?: string, compare?: string, include_trend?: bool, sort?: AnalyticsSort, limit?: int, cursor?: string}
 * @phpstan-type AnalyticsSort array{metric: string, direction: string}
 * @phpstan-type GetDomainQuery array{include?: list<string>}
 * @phpstan-type GetProjectQuery array{include?: list<string>}
 * @phpstan-type GetRouteQuery array{include_machine?: bool, include?: list<string>}
 * @phpstan-type GetStatsQuery array{from: string, to: string, project_id?: string|null, include_machine?: bool}
 * @phpstan-type GetTeamQuery array{include?: list<string>}
 * @phpstan-type ListDomainsQuery array{page?: array{size?: int, cursor?: string}, sort?: list<string>, filter?: array{project?: string, status?: string, domain?: string}}
 * @phpstan-type ListMessageEventsQuery array{page?: array{size?: int, cursor?: string}, include_machine_events?: bool, sort?: list<string>}
 * @phpstan-type ListMessagesQuery array{sort?: list<string>, filter?: array{search?: string, from_email?: string, subject?: string, tags?: list<ListMessagesQueryFilterTagsItem>|string, overdue?: string, project?: string, type?: string, status?: string, delivery_mode?: string, route_id?: string, domain_id?: string, tag?: string, from_date?: string, to_date?: string}, page?: array{size?: int, cursor?: string}}
 * @phpstan-type ListMessagesQueryFilter array{tags?: list<ListMessagesQueryFilterTagsItem>}
 * @phpstan-type ListMessagesQueryFilterTagsItem array{name?: string, value?: string}
 * @phpstan-type ListProjectsQuery array{page?: array{size?: int, cursor?: string}, filter?: array{search?: string}, sort?: list<string>}
 * @phpstan-type ListRoutesQuery array{page?: array{size?: int, cursor?: string}, sort?: list<string>, filter?: array{route_type?: string, is_default?: bool, search?: string}}
 * @phpstan-type ListSuppressionsQuery array{page?: array{size?: int, cursor?: string}, sort?: list<string>, filter?: array{scope?: string, route_id?: string, project_id?: string, value?: string, reason?: string, startDate?: string, endDate?: string}}
 * @phpstan-type ListTeamMembersQuery array{page?: array{size?: int, cursor?: string}}
 * @phpstan-type ListWebhookDeliveriesQuery array{cursor?: string, sort?: list<string>, filter?: array{status?: string, event_type?: string, from_date?: string, to_date?: string}}
 * @phpstan-type ListWebhooksQuery array{page?: array{size?: int}, cursor?: string, sort?: list<string>, filter?: array{project?: string, enabled?: bool, event?: string, route_id?: string, scope?: string, search?: string}}
 * @phpstan-type MessageAttachmentInput array{filename: string, content: string, content_type?: string|null, content_id?: string|null}
 * @phpstan-type MessageTagInput array{name: string, value: string}
 * @phpstan-type ModelNotFoundException ErrorMessage
 * @phpstan-type ReportForwardingRequest array{destination: string}
 * @phpstan-type RescheduleMessageRequest array{scheduled_at: string}
 * @phpstan-type SendBatchMailRequest list<SendMailRequest>
 * @phpstan-type SendBatchMailResponse list<SendMailResponse>
 * @phpstan-type SendMailRequest array{route?: string, from: string, to: list<string>, cc?: list<string>, bcc?: list<string>, reply_to?: list<string>, subject: string, scheduled_at?: string, sandbox_result?: string, headers?: array<string, string>, metadata?: array<string, string>, tag?: string|null, tags?: list<MessageTagInput>, settings?: SendMailRequestSettings, html?: string|null, text?: string|null, attachments?: list<MessageAttachmentInput>}
 * @phpstan-type SendMailRequestSettings array{track_opens?: bool, track_clicks?: bool, tls?: string}
 * @phpstan-type StoreDomainData array{domain: string}
 * @phpstan-type StoreProjectData array{name: string, smtp_enabled?: bool, delivery_mode?: string, initial_routes?: string, short_token?: bool, redact_email_content?: bool}
 * @phpstan-type StoreRouteData array{name: string, route_type: string, slug?: string|null, settings?: UpdateRouteSettingsData|null, inbound_settings?: UpdateRouteInboundSettingsData|null, inbound_domain?: string|null, inbound_spam_threshold?: float|int|null, attachment_delivery?: string|null}
 * @phpstan-type StoreSuppressionData array{email?: string|null, emails?: list<string>|null, reason: string, scope: string, route_id?: string|null, project_id?: string|null, applies_to?: string|null}
 * @phpstan-type StoreWebhookData array{name: string, url: string, events: list<string>, enabled?: bool|null, include_machine_events?: bool|null, delivery_mode_filter?: string|null, scope?: string|null, project_ids?: list<string>, route_ids?: list<string>, route_id?: string|null, basic_auth?: WebhookBasicAuthData|null}
 * @phpstan-type TooManyRequests ErrorMessage
 * @phpstan-type UpdateDomainProjectsData array{project_ids: list<string>}
 * @phpstan-type UpdateProjectData array{name?: string|null, smtp_enabled?: bool|null, redact_email_content?: bool|null, delivery_mode?: string|null, default_route_id?: string|null}
 * @phpstan-type UpdateRouteData array{name?: string|null, settings?: UpdateRouteSettingsData|null, inbound_settings?: UpdateRouteInboundSettingsData|null, inbound_domain?: string|null, inbound_spam_threshold?: float|int|null, attachment_delivery?: string|null}
 * @phpstan-type UpdateRouteInboundSettingsData array{inbound_domain?: string|null, inbound_spam_threshold?: float|int|null, attachment_delivery?: string|null}
 * @phpstan-type UpdateRouteSettingsData array{track_opens?: bool|null, track_clicks?: bool|null, generate_plaintext_fallback?: bool|null, suppress_auto_responders?: bool|null, suppress_disposable_recipients?: bool|null, tls?: string|null, disable_hosted_unsubscribe?: bool|null, redact_email_content?: bool|null}
 * @phpstan-type UpdateTeamData array{name?: string}
 * @phpstan-type UpdateTeamMemberAssignmentData array{role_id: string, project_access: UpdateTeamMemberAssignmentDataProjectAccess}
 * @phpstan-type UpdateTeamMemberAssignmentDataProjectAccess array{scope: string, project_ids?: list<string>}
 * @phpstan-type UpdateWebhookData array{name?: string, url?: string, events?: list<string>, enabled?: bool, include_machine_events?: bool, delivery_mode_filter?: string, scope?: string, project_ids?: list<string>, route_ids?: list<string>, route_id?: string|null, basic_auth?: WebhookBasicAuthData|null}
 * @phpstan-type ValidationException ValidationError
 * @phpstan-type VerifyReportForwardingRequest array{code: string}
 * @phpstan-type WebhookBasicAuthData array{username: string, password: string}
 */
final class ApiTypes
{
    private function __construct()
    {
    }
}
