<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * A page of a cursor-paginated list.
 *
 * Pass `next_cursor` back as the cursor query parameter to read the next page;
 * it is `null` on the last page. Iterating the page yields the items of `data`.
 *
 * @template T
 *
 * @property-read list<T> $data
 * @property-read string|null $path Base path for paginator generated URLs.
 * @property-read int $per_page Number of items shown per page.
 * @property-read string|null $next_cursor The "cursor" that points to the next set of items.
 * @property-read string|null $next_page_url
 * @property-read string|null $prev_cursor The "cursor" that points to the previous set of items.
 * @property-read string|null $prev_page_url
 *
 * @implements \IteratorAggregate<int, T>
 */
abstract class CursorPage extends ApiObject implements \Countable, \IteratorAggregate
{
    /**
     * Whether another page follows this one.
     */
    public function hasMore(): bool
    {
        $cursor = $this->next_cursor;

        return is_string($cursor) && $cursor !== '';
    }

    /**
     * @return \ArrayIterator<int, T>
     */
    public function getIterator(): \ArrayIterator
    {
        $data = $this->data;

        return new \ArrayIterator(is_array($data) ? array_values($data) : []);
    }

    public function count(): int
    {
        $data = $this->data;

        return is_array($data) ? count($data) : 0;
    }
}
