<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * A page of a cursor-paginated list.
 *
 * Pass `next_cursor` back as the cursor query parameter to read the next page;
 * it is `null` on the last page. Iterating the page yields the items of `data`.
 *
 * @template T
 *
 * @property-read list<T> $data
 * @property-read string|null $path Base path for paginator generated URLs.
 * @property-read int $per_page Number of items shown per page.
 * @property-read string|null $next_cursor The "cursor" that points to the next set of items.
 * @property-read string|null $next_page_url
 * @property-read string|null $prev_cursor The "cursor" that points to the previous set of items.
 * @property-read string|null $prev_page_url
 *
 * @implements \IteratorAggregate<int, T>
 */
abstract class CursorPage extends ApiObject implements \Countable, \IteratorAggregate
{
    /**
     * Whether another page follows this one.
     */
    public function hasMore(): bool
    {
        $cursor = $this->next_cursor;

        return is_string($cursor) && $cursor !== '';
    }

    /**
     * @return \ArrayIterator<int, T>
     */
    public function getIterator(): \ArrayIterator
    {
        $data = $this->data;

        return new \ArrayIterator(is_array($data) ? array_values($data) : []);
    }

    public function count(): int
    {
        $data = $this->data;

        return is_array($data) ? count($data) : 0;
    }
}
