<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * One of SuppressionDeletedResponse, SuppressionReviewResponse, as one class with the fields of each.
 *
 * @property-read bool $success
 * @property-read string $status Known values: SuppressionReviewResponseStatus::*.
 * @property-read string $message Human-readable confirmation.
 * @property-read float|int|null $confidence Optional. Confidence of the automated removal assessment, when one ran.
 * @property-read string|null $ticket_identifier Optional. The identifier of the support ticket that reviews the removal.
 */
final class DeleteSuppressionResponse extends ApiObject
{
}
