<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * | |
 * |---|
 * | `active` <br/> The record is active and verified. |
 * | `failed` <br/> The record could not be verified. |
 * | `pending` <br/> The record is pending verification. |
 *
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class DnsRecordStatus
{
    public const ACTIVE = 'active';
    public const FAILED = 'failed';
    public const PENDING = 'pending';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::ACTIVE,
        self::FAILED,
        self::PENDING,
    ];

    private function __construct()
    {
    }
}
