<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * All required DNS records of the domain passed verification.
 *
 * @property-read string $message Human-readable verification result.
 * @property-read list<DnsVerificationFailedRecord> $recommended_failed_records Recommended records that did not pass verification. They do not block verification.
 */
final class DnsVerificationSuccessResponse extends ApiObject
{
    protected const CASTS = [
        'recommended_failed_records' => ['list', DnsVerificationFailedRecord::class],
    ];
}
