<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * One or more required DNS records of the domain did not pass verification.
 *
 * @property-read string $message Human-readable verification result.
 * @property-read list<DnsVerificationFailedRecord> $failed_records Required records that did not pass verification.
 * @property-read list<DnsVerificationError> $errors Verification errors of every failed record, including recommended records.
 * @property-read int $failed_count The number of required records that failed.
 * @property-read int $total_count The number of required records.
 */
final class DnsVerificationFailureResponse extends ApiObject
{
    protected const CASTS = [
        'failed_records' => ['list', DnsVerificationFailedRecord::class],
        'errors' => ['list', DnsVerificationError::class],
    ];
}
