<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * One or more required DNS records of the domain did not pass verification.
 *
 * @property-read string $message Human-readable verification result.
 * @property-read list<DnsVerificationFailedRecord> $failed_records Required records that did not pass verification.
 * @property-read list<DnsVerificationError> $errors Verification errors of every failed record, including recommended records.
 * @property-read int $failed_count The number of required records that failed.
 * @property-read int $total_count The number of required records.
 */
final class DnsVerificationFailureResponse extends ApiObject
{
    protected const CASTS = [
        'failed_records' => ['list', DnsVerificationFailedRecord::class],
        'errors' => ['list', DnsVerificationError::class],
    ];
}
