<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read DnsVerificationResultDataDmarcSpfAlignmentIssue|null $dmarc_spf_alignment_issue
 * @property-read bool $verified
 * @property-read string|null $error
 * @property-read string|null $expected_record
 * @property-read string|null $found_record
 * @property-read string|null $dmarc_policy_domain
 * @property-read string|null $dmarc_effective_policy Known values: DmarcPolicy::*.
 */
final class DnsVerificationResultData extends ApiObject
{
    protected const CASTS = [
        'dmarc_spf_alignment_issue' => DnsVerificationResultDataDmarcSpfAlignmentIssue::class,
    ];
}
