<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $type Known values: RecordType::*.
 * @property-read string $hostname
 * @property-read string $fqdn
 * @property-read string $content
 * @property-read string $status Known values: DnsRecordStatus::*.
 * @property-read string $purpose Known values: DnsRecordPurpose::*.
 * @property-read string $verification_scope Known values: DnsVerificationScope::*.
 * @property-read bool $required_for_verification
 * @property-read string|null $verified_at
 * @property-read string|null $last_checked_at
 */
final class DomainDnsRecordData extends ApiObject
{
}
