<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * | |
 * |---|
 * | `verified` <br/> The domain is active and verified. |
 * | `partially_verified` <br/> Some DNS records of the domain could not be verified. |
 * | `pending_verification` <br/> The domain is new and verification is pending. |
 * | `failed_verification` <br/> The domain verification failed. |
 *
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class DomainStatus
{
    public const VERIFIED = 'verified';
    public const PARTIALLY_VERIFIED = 'partially_verified';
    public const PENDING_VERIFICATION = 'pending_verification';
    public const FAILED_VERIFICATION = 'failed_verification';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::VERIFIED,
        self::PARTIALLY_VERIFIED,
        self::PENDING_VERIFICATION,
        self::FAILED_VERIFICATION,
    ];

    private function __construct()
    {
    }
}
