<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $domain
 * @property-read string $dkim_mode Known values: DkimMode::*.
 * @property-read bool $rotation_ready
 * @property-read string|null $status_changed_at
 * @property-read list<DomainDnsRecordData>|null $dns_records Optional.
 * @property-read list<DomainDataProjectsItem>|null $projects Optional.
 * @property-read string $created_at
 */
final class DomainData extends ApiObject
{
    protected const CASTS = [
        'dns_records' => ['list', DomainDnsRecordData::class],
        'projects' => ['list', DomainDataProjectsItem::class],
    ];
}
