<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $type Known values: RecordType::*.
 * @property-read string $hostname
 * @property-read string $fqdn
 * @property-read string $content
 * @property-read string $status Known values: DnsRecordStatus::*.
 * @property-read string $purpose Known values: DnsRecordPurpose::*.
 * @property-read string $verification_scope Known values: DnsVerificationScope::*.
 * @property-read bool $required_for_verification
 * @property-read string|null $verified_at
 * @property-read string|null $last_checked_at
 */
final class DomainDnsRecordData extends ApiObject
{
}
