<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * | |
 * |---|
 * | `verified` <br/> The domain is active and verified. |
 * | `partially_verified` <br/> Some DNS records of the domain could not be verified. |
 * | `pending_verification` <br/> The domain is new and verification is pending. |
 * | `failed_verification` <br/> The domain verification failed. |
 *
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class DomainStatus
{
    public const VERIFIED = 'verified';
    public const PARTIALLY_VERIFIED = 'partially_verified';
    public const PENDING_VERIFICATION = 'pending_verification';
    public const FAILED_VERIFICATION = 'failed_verification';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::VERIFIED,
        self::PARTIALLY_VERIFIED,
        self::PENDING_VERIFICATION,
        self::FAILED_VERIFICATION,
    ];

    private function __construct()
    {
    }
}
