<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class ListRoutesQuerySortItem
{
    public const NAME = 'name';
    public const NAME_DESC = '-name';
    public const SLUG = 'slug';
    public const SLUG_DESC = '-slug';
    public const CREATED_AT = 'created_at';
    public const CREATED_AT_DESC = '-created_at';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::NAME,
        self::NAME_DESC,
        self::SLUG,
        self::SLUG_DESC,
        self::CREATED_AT,
        self::CREATED_AT_DESC,
    ];

    private function __construct()
    {
    }
}
