<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class ListMessagesQuerySortItem
{
    public const TYPE = 'type';
    public const TYPE_DESC = '-type';
    public const STATUS = 'status';
    public const STATUS_DESC = '-status';
    public const FROM_EMAIL = 'from_email';
    public const FROM_EMAIL_DESC = '-from_email';
    public const SUBJECT = 'subject';
    public const SUBJECT_DESC = '-subject';
    public const CREATED_AT = 'created_at';
    public const CREATED_AT_DESC = '-created_at';
    public const STATUS_CHANGED_AT = 'status_changed_at';
    public const STATUS_CHANGED_AT_DESC = '-status_changed_at';
    public const SCHEDULED_AT = 'scheduled_at';
    public const SCHEDULED_AT_DESC = '-scheduled_at';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::TYPE,
        self::TYPE_DESC,
        self::STATUS,
        self::STATUS_DESC,
        self::FROM_EMAIL,
        self::FROM_EMAIL_DESC,
        self::SUBJECT,
        self::SUBJECT_DESC,
        self::CREATED_AT,
        self::CREATED_AT_DESC,
        self::STATUS_CHANGED_AT,
        self::STATUS_CHANGED_AT_DESC,
        self::SCHEDULED_AT,
        self::SCHEDULED_AT_DESC,
    ];

    private function __construct()
    {
    }
}
