<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class ListMessagesQuerySortItem
{
    public const TYPE = 'type';
    public const TYPE_DESC = '-type';
    public const STATUS = 'status';
    public const STATUS_DESC = '-status';
    public const FROM_EMAIL = 'from_email';
    public const FROM_EMAIL_DESC = '-from_email';
    public const SUBJECT = 'subject';
    public const SUBJECT_DESC = '-subject';
    public const CREATED_AT = 'created_at';
    public const CREATED_AT_DESC = '-created_at';
    public const STATUS_CHANGED_AT = 'status_changed_at';
    public const STATUS_CHANGED_AT_DESC = '-status_changed_at';
    public const SCHEDULED_AT = 'scheduled_at';
    public const SCHEDULED_AT_DESC = '-scheduled_at';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::TYPE,
        self::TYPE_DESC,
        self::STATUS,
        self::STATUS_DESC,
        self::FROM_EMAIL,
        self::FROM_EMAIL_DESC,
        self::SUBJECT,
        self::SUBJECT_DESC,
        self::CREATED_AT,
        self::CREATED_AT_DESC,
        self::STATUS_CHANGED_AT,
        self::STATUS_CHANGED_AT_DESC,
        self::SCHEDULED_AT,
        self::SCHEDULED_AT_DESC,
    ];

    private function __construct()
    {
    }
}
