<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $message_id
 * @property-read string $event Known values: MessageEventType::*.
 * @property-read string|null $tag
 * @property-read list<MessageTag> $tags
 * @property-read array<string, mixed>|null $metadata
 * @property-read string $timestamp
 */
final class MessageEventData extends ApiObject
{
    protected const CASTS = [
        'tags' => ['list', MessageTag::class],
    ];
}
