<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $email
 * @property-read string|null $name
 * @property-read string|null $sandbox_result The simulated result for this recipient in a Sandbox project. Lettermint test addresses override the message result. Null for Live messages. Known values: SandboxResult::*.
 */
final class MessageRecipientData extends ApiObject
{
}
