<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class MessageStatus
{
    public const SCHEDULED = 'scheduled';
    public const PENDING = 'pending';
    public const QUEUED = 'queued';
    public const QUARANTINED = 'quarantined';
    public const SUPPRESSED = 'suppressed';
    public const PROCESSED = 'processed';
    public const DELIVERED = 'delivered';
    public const OPENED = 'opened';
    public const CLICKED = 'clicked';
    public const SOFT_BOUNCED = 'soft_bounced';
    public const HARD_BOUNCED = 'hard_bounced';
    public const SPAM_COMPLAINT = 'spam_complaint';
    public const FAILED = 'failed';
    public const BLOCKED = 'blocked';
    public const POLICY_REJECTED = 'policy_rejected';
    public const UNSUBSCRIBED = 'unsubscribed';
    public const CANCELED = 'canceled';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::SCHEDULED,
        self::PENDING,
        self::QUEUED,
        self::QUARANTINED,
        self::SUPPRESSED,
        self::PROCESSED,
        self::DELIVERED,
        self::OPENED,
        self::CLICKED,
        self::SOFT_BOUNCED,
        self::HARD_BOUNCED,
        self::SPAM_COMPLAINT,
        self::FAILED,
        self::BLOCKED,
        self::POLICY_REJECTED,
        self::UNSUBSCRIBED,
        self::CANCELED,
    ];

    private function __construct()
    {
    }
}
