<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $type Known values: MessageType::*.
 * @property-read string $status Known values: MessageStatus::*.
 * @property-read string $delivery_mode Known values: DeliveryMode::*.
 * @property-read string|null $sandbox_result Known values: SandboxResult::*.
 * @property-read string|null $scheduled_at
 * @property-read float|int|null $spam_score Optional. Overall spam assessment score. Scores below 5 are clean, 5 through 10 indicate potential spam, scores above 10 and below 15 are likely spam, and 15 or higher is definite spam. Null means no assessment is available. Available on plans with Spam Insights.
 * @property-read string $from_email
 * @property-read string|null $from_name
 * @property-read string|null $subject
 * @property-read list<MessageRecipientData>|null $to
 * @property-read list<MessageRecipientData>|null $cc
 * @property-read list<MessageRecipientData>|null $bcc
 * @property-read list<string>|null $reply_to
 * @property-read string|null $tag
 * @property-read list<MessageTag> $tags
 * @property-read string|null $status_changed_at
 * @property-read string $created_at
 */
final class MessageListData extends ApiObject
{
    protected const CASTS = [
        'to' => ['list', MessageRecipientData::class],
        'cc' => ['list', MessageRecipientData::class],
        'bcc' => ['list', MessageRecipientData::class],
        'tags' => ['list', MessageTag::class],
    ];
}
