<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class MessageEventType
{
    public const SCHEDULED = 'scheduled';
    public const RESCHEDULED = 'rescheduled';
    public const CANCELED = 'canceled';
    public const RELEASED = 'released';
    public const QUEUED = 'queued';
    public const PROCESSED = 'processed';
    public const SUPPRESSED = 'suppressed';
    public const DELIVERED = 'delivered';
    public const AUTO_REPLIED = 'auto_replied';
    public const SOFT_BOUNCED = 'soft_bounced';
    public const HARD_BOUNCED = 'hard_bounced';
    public const SPAM_COMPLAINT = 'spam_complaint';
    public const FAILED = 'failed';
    public const BLOCKED = 'blocked';
    public const POLICY_REJECTED = 'policy_rejected';
    public const UNSUBSCRIBED = 'unsubscribed';
    public const OPENED = 'opened';
    public const CLICKED = 'clicked';
    public const INBOUND_RECEIVED = 'inbound_received';
    public const INBOUND_QUEUED = 'inbound_queued';
    public const INBOUND_SPAM_BLOCKED = 'inbound_spam_blocked';
    public const INBOUND_RELEASED = 'inbound_released';
    public const INBOUND_PROCESSED = 'inbound_processed';
    public const INBOUND_RETRY = 'inbound_retry';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::SCHEDULED,
        self::RESCHEDULED,
        self::CANCELED,
        self::RELEASED,
        self::QUEUED,
        self::PROCESSED,
        self::SUPPRESSED,
        self::DELIVERED,
        self::AUTO_REPLIED,
        self::SOFT_BOUNCED,
        self::HARD_BOUNCED,
        self::SPAM_COMPLAINT,
        self::FAILED,
        self::BLOCKED,
        self::POLICY_REJECTED,
        self::UNSUBSCRIBED,
        self::OPENED,
        self::CLICKED,
        self::INBOUND_RECEIVED,
        self::INBOUND_QUEUED,
        self::INBOUND_SPAM_BLOCKED,
        self::INBOUND_RELEASED,
        self::INBOUND_PROCESSED,
        self::INBOUND_RETRY,
    ];

    private function __construct()
    {
    }
}
