<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * An accepted message that is queued for delivery.
 *
 * @property-read string $message_id
 * @property-read string $status
 * @property-read bool|null $sandbox Optional. Present when the project uses Sandbox delivery.
 * @property-read string|null $sandbox_result Optional. The simulated delivery result. Present when the project uses Sandbox delivery. Known values: SandboxResult::*.
 */
final class PendingSendMailResponse extends ApiObject
{
}
