<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * An accepted message that is queued for delivery.
 *
 * @property-read string $message_id
 * @property-read string $status
 * @property-read bool|null $sandbox Optional. Present when the project uses Sandbox delivery.
 * @property-read string|null $sandbox_result Optional. The simulated delivery result. Present when the project uses Sandbox delivery. Known values: SandboxResult::*.
 */
final class PendingSendMailResponse extends ApiObject
{
}
