<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read string $delivery_mode Known values: DeliveryMode::*.
 * @property-read bool $smtp_enabled
 * @property-read bool $redact_email_content
 * @property-read string|null $default_route_id
 * @property-read string|null $token_generated_at
 * @property-read string|null $token_last_used_at
 * @property-read string|null $token_last_used_ip
 * @property-read list<RouteData>|null $routes Optional.
 * @property-read int|null $routes_count Optional.
 * @property-read list<DomainData>|null $domains Optional.
 * @property-read int|null $domains_count Optional.
 * @property-read MessageStatsData|null $last_28_days Optional.
 * @property-read string $created_at
 * @property-read string $updated_at
 */
final class ProjectData extends ApiObject
{
    protected const CASTS = [
        'routes' => ['list', RouteData::class],
        'domains' => ['list', DomainData::class],
        'last_28_days' => MessageStatsData::class,
    ];
}
