<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read string $delivery_mode Known values: DeliveryMode::*.
 * @property-read bool $smtp_enabled
 * @property-read bool $redact_email_content
 * @property-read string|null $default_route_id
 * @property-read string|null $token_generated_at
 * @property-read string|null $token_last_used_at
 * @property-read string|null $token_last_used_ip
 * @property-read list<RouteData>|null $routes Optional.
 * @property-read int|null $routes_count Optional.
 * @property-read list<DomainData>|null $domains Optional.
 * @property-read int|null $domains_count Optional.
 * @property-read MessageStatsData|null $last_28_days Optional.
 * @property-read string $created_at
 * @property-read string $updated_at
 */
final class ProjectData extends ApiObject
{
    protected const CASTS = [
        'routes' => ['list', RouteData::class],
        'domains' => ['list', DomainData::class],
        'last_28_days' => MessageStatsData::class,
    ];
}
