<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class RbacPermission
{
    public const TEAM_MANAGE = 'team:manage';
    public const BILLING_MANAGE = 'billing:manage';
    public const SECURITY_MANAGE = 'security:manage';
    public const AUDIT_READ = 'audit:read';
    public const SUPPORT_MANAGE = 'support:manage';
    public const MEMBERS_READ = 'members:read';
    public const MEMBERS_MANAGE = 'members:manage';
    public const ROLES_MANAGE = 'roles:manage';
    public const TEAM_TOKENS_READ = 'team_tokens:read';
    public const TEAM_TOKENS_MANAGE = 'team_tokens:manage';
    public const TEAM_TOKENS_ROTATE = 'team_tokens:rotate';
    public const TEAM_TOKENS_REVOKE = 'team_tokens:revoke';
    public const PROJECTS_CREATE = 'projects:create';
    public const TEAM_SUPPRESSIONS_READ = 'team_suppressions:read';
    public const TEAM_SUPPRESSIONS_ADD = 'team_suppressions:add';
    public const TEAM_SUPPRESSIONS_REMOVE = 'team_suppressions:remove';
    public const PROJECTS_READ = 'projects:read';
    public const PROJECTS_MANAGE = 'projects:manage';
    public const PROJECTS_DELETE = 'projects:delete';
    public const ROUTES_READ = 'routes:read';
    public const ROUTES_MANAGE = 'routes:manage';
    public const ROUTES_DELETE = 'routes:delete';
    public const DOMAINS_READ = 'domains:read';
    public const DOMAINS_MANAGE = 'domains:manage';
    public const DOMAINS_DELETE = 'domains:delete';
    public const PROJECT_TOKENS_READ = 'project_tokens:read';
    public const PROJECT_TOKENS_MANAGE = 'project_tokens:manage';
    public const PROJECT_TOKENS_ROTATE = 'project_tokens:rotate';
    public const PROJECT_TOKENS_REVOKE = 'project_tokens:revoke';
    public const WEBHOOKS_READ = 'webhooks:read';
    public const WEBHOOKS_MANAGE = 'webhooks:manage';
    public const WEBHOOKS_DELETE = 'webhooks:delete';
    public const WEBHOOKS_ROTATE_SECRET = 'webhooks:rotate_secret';
    public const STATS_READ = 'stats:read';
    public const ANALYTICS_READ = 'analytics:read';
    public const MESSAGES_READ = 'messages:read';
    public const MESSAGES_READ_CONTENT = 'messages:read_content';
    public const MESSAGES_SEND = 'messages:send';
    public const SUPPRESSIONS_READ = 'suppressions:read';
    public const SUPPRESSIONS_ADD = 'suppressions:add';
    public const SUPPRESSIONS_REMOVE = 'suppressions:remove';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::TEAM_MANAGE,
        self::BILLING_MANAGE,
        self::SECURITY_MANAGE,
        self::AUDIT_READ,
        self::SUPPORT_MANAGE,
        self::MEMBERS_READ,
        self::MEMBERS_MANAGE,
        self::ROLES_MANAGE,
        self::TEAM_TOKENS_READ,
        self::TEAM_TOKENS_MANAGE,
        self::TEAM_TOKENS_ROTATE,
        self::TEAM_TOKENS_REVOKE,
        self::PROJECTS_CREATE,
        self::TEAM_SUPPRESSIONS_READ,
        self::TEAM_SUPPRESSIONS_ADD,
        self::TEAM_SUPPRESSIONS_REMOVE,
        self::PROJECTS_READ,
        self::PROJECTS_MANAGE,
        self::PROJECTS_DELETE,
        self::ROUTES_READ,
        self::ROUTES_MANAGE,
        self::ROUTES_DELETE,
        self::DOMAINS_READ,
        self::DOMAINS_MANAGE,
        self::DOMAINS_DELETE,
        self::PROJECT_TOKENS_READ,
        self::PROJECT_TOKENS_MANAGE,
        self::PROJECT_TOKENS_ROTATE,
        self::PROJECT_TOKENS_REVOKE,
        self::WEBHOOKS_READ,
        self::WEBHOOKS_MANAGE,
        self::WEBHOOKS_DELETE,
        self::WEBHOOKS_ROTATE_SECRET,
        self::STATS_READ,
        self::ANALYTICS_READ,
        self::MESSAGES_READ,
        self::MESSAGES_READ_CONTENT,
        self::MESSAGES_SEND,
        self::SUPPRESSIONS_READ,
        self::SUPPRESSIONS_ADD,
        self::SUPPRESSIONS_REMOVE,
    ];

    private function __construct()
    {
    }
}
