<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $project_id
 * @property-read string $slug
 * @property-read string $name
 * @property-read string $route_type Known values: RouteType::*.
 * @property-read bool $is_default
 * @property-read string|null $inbound_address Optional. Permanent compatibility address for this inbound route (`<route-uuid-without-hyphens>@inbound.lettermint.co`). It keeps working alongside the catch-all route domain.
 * @property-read string|null $inbound_route_domain Optional. Catch-all receiving domain for this inbound route. Mail to any address at this domain reaches the route. Null for non-inbound routes.
 * @property-read string|null $inbound_mx_hostname Optional.
 * @property-read string|null $inbound_domain Optional.
 * @property-read string|null $inbound_domain_verified_at Optional.
 * @property-read float|int|null $inbound_spam_threshold Optional.
 * @property-read string|null $attachment_delivery Optional. Known values: AttachmentDelivery::*.
 * @property-read RouteDataSettings|null $settings Optional. Route settings available for this route type and team feature access.
 * @property-read ProjectData|null $project Optional.
 * @property-read int|null $webhooks_count Optional.
 * @property-read int|null $suppressed_recipients_count Optional.
 * @property-read list<RouteStatisticData>|null $statistics Optional.
 * @property-read string $created_at
 * @property-read string $updated_at
 */
final class RouteData extends ApiObject
{
    protected const CASTS = [
        'settings' => RouteDataSettings::class,
        'project' => ProjectData::class,
        'statistics' => ['list', RouteStatisticData::class],
    ];
}
