<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Route settings available for this route type and team feature access
 *
 * @property-read bool|null $disable_hosted_unsubscribe Optional.
 * @property-read bool|null $track_opens Optional.
 * @property-read bool|null $track_clicks Optional.
 * @property-read bool|null $generate_plaintext_fallback Optional.
 * @property-read bool|null $suppress_auto_responders Optional.
 * @property-read bool|null $suppress_disposable_recipients Optional.
 * @property-read string|null $tls Optional. Known values: TlsPolicy::*.
 * @property-read bool|null $redact_email_content Optional.
 * @property-read string|null $attachment_delivery Optional. Known values: AttachmentDelivery::*.
 */
final class RouteDataSettings extends ApiObject
{
}
