<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $project_id
 * @property-read string $slug
 * @property-read string $name
 * @property-read string $route_type Known values: RouteType::*.
 * @property-read bool $is_default
 * @property-read string|null $inbound_address Optional. Permanent compatibility address for this inbound route (`<route-uuid-without-hyphens>@inbound.lettermint.co`). It keeps working alongside the catch-all route domain.
 * @property-read string|null $inbound_route_domain Optional. Catch-all receiving domain for this inbound route. Mail to any address at this domain reaches the route. Null for non-inbound routes.
 * @property-read string|null $inbound_mx_hostname Optional.
 * @property-read string|null $inbound_domain Optional.
 * @property-read string|null $inbound_domain_verified_at Optional.
 * @property-read float|int|null $inbound_spam_threshold Optional.
 * @property-read string|null $attachment_delivery Optional. Known values: AttachmentDelivery::*.
 * @property-read RouteDataSettings|null $settings Optional. Route settings available for this route type and team feature access.
 * @property-read ProjectData|null $project Optional.
 * @property-read int|null $webhooks_count Optional.
 * @property-read int|null $suppressed_recipients_count Optional.
 * @property-read list<RouteStatisticData>|null $statistics Optional.
 * @property-read string $created_at
 * @property-read string $updated_at
 */
final class RouteData extends ApiObject
{
    protected const CASTS = [
        'settings' => RouteDataSettings::class,
        'project' => ProjectData::class,
        'statistics' => ['list', RouteStatisticData::class],
    ];
}
