<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $date
 * @property-read int $sent_count
 * @property-read int $delivered_count
 * @property-read int $opened_count
 * @property-read int $clicked_count
 * @property-read int $hard_bounce_count
 * @property-read int $spam_complaint_count
 * @property-read int $inbound_received_count
 * @property-read int|null $observed_opened_count Optional.
 * @property-read int|null $human_opened_count Optional.
 * @property-read int|null $privacy_opened_count Optional.
 * @property-read int|null $effective_opened_count
 * @property-read int|null $machine_opened_count
 * @property-read int|null $machine_clicked_count
 */
final class RouteStatisticData extends ApiObject
{
}
