<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * Route settings available for this route type and team feature access
 *
 * @property-read bool|null $disable_hosted_unsubscribe Optional.
 * @property-read bool|null $track_opens Optional.
 * @property-read bool|null $track_clicks Optional.
 * @property-read bool|null $generate_plaintext_fallback Optional.
 * @property-read bool|null $suppress_auto_responders Optional.
 * @property-read bool|null $suppress_disposable_recipients Optional.
 * @property-read string|null $tls Optional. Known values: TlsPolicy::*.
 * @property-read bool|null $redact_email_content Optional.
 * @property-read string|null $attachment_delivery Optional. Known values: AttachmentDelivery::*.
 */
final class RouteDataSettings extends ApiObject
{
}
