<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class SandboxResult
{
    public const DELIVERED = 'delivered';
    public const HARD_BOUNCED = 'hard_bounced';
    public const SOFT_BOUNCED = 'soft_bounced';
    public const DEFERRED = 'deferred';
    public const FAILED = 'failed';
    public const SUPPRESSED = 'suppressed';
    public const SPAM_COMPLAINT = 'spam_complaint';
    public const AUTO_REPLIED = 'auto_replied';
    public const OPENED = 'opened';
    public const CLICKED = 'clicked';
    public const UNSUBSCRIBED = 'unsubscribed';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::DELIVERED,
        self::HARD_BOUNCED,
        self::SOFT_BOUNCED,
        self::DEFERRED,
        self::FAILED,
        self::SUPPRESSED,
        self::SPAM_COMPLAINT,
        self::AUTO_REPLIED,
        self::OPENED,
        self::CLICKED,
        self::UNSUBSCRIBED,
    ];

    private function __construct()
    {
    }
}
