<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * One of PendingSendMailResponse, ScheduledSendMailResponse, as one class with the fields of each.
 *
 * @property-read string $message_id
 * @property-read string $status Known values: MessageStatus::*.
 * @property-read bool|null $sandbox Optional. Present when the project uses Sandbox delivery.
 * @property-read string|null $sandbox_result Optional. The simulated delivery result. Present when the project uses Sandbox delivery. Known values: SandboxResult::*.
 * @property-read string|null $scheduled_at Optional. The scheduled delivery time in ISO 8601 format.
 */
final class SendMailResponse extends ApiObject
{
}
