<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read int $sent
 * @property-read int $delivered
 * @property-read int $hard_bounced
 * @property-read int $spam_complaints
 * @property-read int|null $opened Null when tracking is not enabled for this context.
 * @property-read int|null $clicked Null when tracking is not enabled for this context.
 * @property-read StatsInboundData $inbound
 * @property-read StatsTypeData|null $transactional Null for team-scoped stats (only available when project_id is specified).
 * @property-read StatsTypeData|null $broadcast Null for team-scoped stats (only available when project_id is specified).
 * @property-read int|null $observed_opened Optional. Human opens plus unresolved privacy-proxy opens.
 * @property-read int|null $human_opened Optional.
 * @property-read int|null $privacy_opened Optional.
 * @property-read int|null $effective_opened
 * @property-read int|null $machine_opened
 * @property-read int|null $machine_clicked
 */
final class StatsTotalsData extends ApiObject
{
    protected const CASTS = [
        'inbound' => StatsInboundData::class,
        'transactional' => StatsTypeData::class,
        'broadcast' => StatsTypeData::class,
    ];
}
