<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $date
 * @property-read int $sent
 * @property-read int $delivered
 * @property-read int $hard_bounced
 * @property-read int $spam_complaints
 * @property-read int|null $opened Null when tracking is not enabled for this context.
 * @property-read int|null $clicked Null when tracking is not enabled for this context.
 * @property-read StatsInboundData $inbound
 * @property-read StatsTypeData|null $transactional Null for team-scoped stats (only available when project_id is specified).
 * @property-read StatsTypeData|null $broadcast Null for team-scoped stats (only available when project_id is specified).
 * @property-read int|null $observed_opened Optional. Human opens plus unresolved privacy-proxy opens.
 * @property-read int|null $human_opened Optional.
 * @property-read int|null $privacy_opened Optional.
 * @property-read int|null $effective_opened
 * @property-read int|null $machine_opened
 * @property-read int|null $machine_clicked
 */
final class StatsDailyData extends ApiObject
{
    protected const CASTS = [
        'inbound' => StatsInboundData::class,
        'transactional' => StatsTypeData::class,
        'broadcast' => StatsTypeData::class,
    ];
}
