<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read string $type Known values: TeamType::*.
 * @property-read string $plan Known values: Plan::*.
 * @property-read int $included_volume Number of emails included in the team's monthly plan.
 * @property-read int $tier Deprecated. Deprecated alias for `included_volume`.
 * @property-read string|null $verified_at
 * @property-read list<string>|null $features Optional.
 * @property-read list<TeamAddonData>|null $addons Optional.
 * @property-read string $created_at
 * @property-read int|null $domains_count Optional.
 * @property-read int|null $projects_count Optional.
 * @property-read int|null $members_count Optional.
 */
final class TeamData extends ApiObject
{
    protected const CASTS = [
        'addons' => ['list', TeamAddonData::class],
    ];
}
