<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $name
 * @property-read string $type Known values: TeamType::*.
 * @property-read string $plan Known values: Plan::*.
 * @property-read int $included_volume Number of emails included in the team's monthly plan.
 * @property-read int $tier Deprecated. Deprecated alias for `included_volume`.
 * @property-read string|null $verified_at
 * @property-read list<string>|null $features Optional.
 * @property-read list<TeamAddonData>|null $addons Optional.
 * @property-read string $created_at
 * @property-read int|null $domains_count Optional.
 * @property-read int|null $projects_count Optional.
 * @property-read int|null $members_count Optional.
 */
final class TeamData extends ApiObject
{
    protected const CASTS = [
        'addons' => ['list', TeamAddonData::class],
    ];
}
