<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $webhook_id
 * @property-read string $event_type Known values: WebhookEvent::*.
 * @property-read string|null $source_scope
 * @property-read string|null $source_project_id
 * @property-read string|null $source_route_id
 * @property-read string $status Known values: WebhookDeliveryStatus::*.
 * @property-read bool $sandbox
 * @property-read int $attempt_number
 * @property-read int|null $http_status_code
 * @property-read int|null $duration_ms
 * @property-read string|null $delivered_at
 * @property-read string $created_at
 */
final class WebhookDeliveryListData extends ApiObject
{
}
