<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class WebhookDeliveryStatus
{
    public const PENDING = 'pending';
    public const SUCCESS = 'success';
    public const FAILED = 'failed';
    public const CLIENT_ERROR = 'client_error';
    public const SERVER_ERROR = 'server_error';
    public const TIMEOUT = 'timeout';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::PENDING,
        self::SUCCESS,
        self::FAILED,
        self::CLIENT_ERROR,
        self::SERVER_ERROR,
        self::TIMEOUT,
    ];

    private function __construct()
    {
    }
}
