<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@80d8ab2a2d73644c2bdee8a4bb9d3565aa017d72 (feat/openapi-named-schemas)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $scope Known values: WebhookScope::*.
 * @property-read list<string> $project_ids
 * @property-read list<string> $route_ids
 * @property-read string|null $route_id Deprecated. Use route_ids.
 * @property-read string $name
 * @property-read string $url
 * @property-read bool $has_basic_auth
 * @property-read list<string> $events
 * @property-read bool $enabled
 * @property-read bool $include_machine_events
 * @property-read string $delivery_mode_filter Known values: WebhookDeliveryModeFilter::*.
 * @property-read string|null $last_called_at
 * @property-read string $created_at
 * @property-read string $updated_at
 */
final class WebhookData extends ApiObject
{
}
