<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@0b4ecbdd237d155305b9aab19efe96b2a4830446 (main)
// sending-openapi.json SHA-256: 53e80a6c21cd8995a02c75dfbef79773242cd0d60a5e6262eb79dc127f779c7f
// team-openapi.json SHA-256: 8b379814a0f501d2c564858bc382a29133535e704cc279545a934db611d587dd
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

/**
 * The values the API documents. The set is open: the API may return a value
 * that is not listed here, and the SDK passes it through as it is.
 */
final class WebhookEvent
{
    public const MESSAGE_CREATED = 'message.created';
    public const MESSAGE_SENT = 'message.sent';
    public const MESSAGE_DELIVERED = 'message.delivered';
    public const MESSAGE_AUTO_REPLIED = 'message.auto_replied';
    public const MESSAGE_HARD_BOUNCED = 'message.hard_bounced';
    public const MESSAGE_SOFT_BOUNCED = 'message.soft_bounced';
    public const MESSAGE_SPAM_COMPLAINT = 'message.spam_complaint';
    public const MESSAGE_FAILED = 'message.failed';
    public const MESSAGE_SUPPRESSED = 'message.suppressed';
    public const MESSAGE_UNSUBSCRIBED = 'message.unsubscribed';
    public const MESSAGE_OPENED = 'message.opened';
    public const MESSAGE_CLICKED = 'message.clicked';
    public const MESSAGE_INBOUND = 'message.inbound';
    public const MESSAGE_POLICY_REJECTED = 'message.policy_rejected';
    public const MESSAGE_SCHEDULED = 'message.scheduled';
    public const MESSAGE_RESCHEDULED = 'message.rescheduled';
    public const MESSAGE_CANCELED = 'message.canceled';
    public const MESSAGE_RELEASED = 'message.released';
    public const SUPPRESSION_ADDED = 'suppression.added';
    public const SUPPRESSION_REMOVED = 'suppression.removed';
    public const WEBHOOK_TEST = 'webhook.test';

    /** Every value known when this SDK was generated. */
    public const VALUES = [
        self::MESSAGE_CREATED,
        self::MESSAGE_SENT,
        self::MESSAGE_DELIVERED,
        self::MESSAGE_AUTO_REPLIED,
        self::MESSAGE_HARD_BOUNCED,
        self::MESSAGE_SOFT_BOUNCED,
        self::MESSAGE_SPAM_COMPLAINT,
        self::MESSAGE_FAILED,
        self::MESSAGE_SUPPRESSED,
        self::MESSAGE_UNSUBSCRIBED,
        self::MESSAGE_OPENED,
        self::MESSAGE_CLICKED,
        self::MESSAGE_INBOUND,
        self::MESSAGE_POLICY_REJECTED,
        self::MESSAGE_SCHEDULED,
        self::MESSAGE_RESCHEDULED,
        self::MESSAGE_CANCELED,
        self::MESSAGE_RELEASED,
        self::SUPPRESSION_ADDED,
        self::SUPPRESSION_REMOVED,
        self::WEBHOOK_TEST,
    ];

    private function __construct()
    {
    }
}
