<?php

// Generated by lettermint/sdk-generator — do not edit.
// Spec: lettermint/lettermint@bff20c7d86dd05b926713f89c0ad716ef630ae21 (main)
// sending-openapi.json SHA-256: 958303afdf2971b372cab97e72845db2568bc0b6cb6f5c41b2a0dad0386df15d
// team-openapi.json SHA-256: 04718e1e006be90fe586f30754a73a4fd69233119dc36862ded9fb98d69aa138
// Naming profile: next

declare(strict_types=1);

namespace Lettermint\Types;

use Lettermint\ApiObject;

/**
 * @property-read string $id
 * @property-read string $webhook_id
 * @property-read string $event_type Known values: WebhookEvent::*.
 * @property-read string|null $source_scope
 * @property-read string|null $source_project_id
 * @property-read string|null $source_route_id
 * @property-read string $status Known values: WebhookDeliveryStatus::*.
 * @property-read bool $sandbox
 * @property-read int $attempt_number
 * @property-read int|null $http_status_code
 * @property-read int|null $duration_ms
 * @property-read list<string> $payload
 * @property-read string|null $response_body
 * @property-read list<string>|null $response_headers
 * @property-read string|null $error_message
 * @property-read string|null $delivered_at
 * @property-read string $timestamp
 */
final class WebhookDeliveryData extends ApiObject
{
}
