<?php

/*
 * Regenerates (or, with --check, verifies) src/Types/ with the private
 * lettermint/sdk-generator. Set LETTERMINT_SDK_GENERATOR to its checkout
 * (default: ../sdk-generator next to this repository).
 *
 * Without the generator (CI, contributors without access), --check only
 * verifies that every generated file carries the generator header with the
 * same spec commit and hashes, so that hand edits that drop it are caught.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$out = $root.'/src/Types';
$check = in_array('--check', $argv, true);
$generator = getenv('LETTERMINT_SDK_GENERATOR') ?: $root.'/../sdk-generator';
if (! str_starts_with($generator, '/')) {
    $generator = $root.'/'.$generator;
}
$available = is_dir($generator.'/lettermint_sdkgen') && is_file($generator.'/spec.next.lock.json');

if ($available) {
    $command = [
        'python3', '-m', 'lettermint_sdkgen', 'emit', 'php',
        '--profile', 'next', '--lock', 'spec.next.lock.json', '--out', $out,
    ];
    if ($check) {
        $command[] = '--check';
    }
    $process = proc_open($command, [STDIN, STDOUT, STDERR], $pipes, $generator);
    exit($process === false ? 1 : proc_close($process));
}

if (! $check) {
    fwrite(STDERR, "The SDK generator was not found at {$generator}. Set LETTERMINT_SDK_GENERATOR to its checkout.\n");
    exit(1);
}

$files = glob($out.'/*.php') ?: [];
if ($files === []) {
    fwrite(STDERR, "src/Types/ has no generated files. Regenerate them.\n");
    exit(1);
}
$expected = null;
foreach ($files as $file) {
    $lines = array_slice(explode("\n", (string) file_get_contents($file)), 0, 7);
    $header = array_slice($lines, 2, 5);
    $valid = $lines[0] === '<?php'
        && $lines[1] === ''
        && $header[0] === '// Generated by lettermint/sdk-generator — do not edit.'
        && preg_match('/^\/\/ Spec: lettermint\/lettermint@[0-9a-f]{40}( \(.+\))?$/', $header[1]) === 1
        && preg_match('/^\/\/ sending-openapi\.json SHA-256: [0-9a-f]{64}$/', $header[2]) === 1
        && preg_match('/^\/\/ team-openapi\.json SHA-256: [0-9a-f]{64}$/', $header[3]) === 1
        && $header[4] === '// Naming profile: next';
    if (! $valid) {
        fwrite(STDERR, 'src/Types/'.basename($file)." is missing the generator header. Regenerate it; do not edit it by hand.\n");
        exit(1);
    }
    $expected ??= $header;
    if ($header !== $expected) {
        fwrite(STDERR, 'src/Types/'.basename($file)." comes from a different spec than the other generated files. Regenerate them all.\n");
        exit(1);
    }
}
echo "SDK generator not found at {$generator}; checked the headers of ".count($files)." generated files only.\n";
echo $expected[1]."\n";
